"""empty message

Revision ID: e61159146ed7
Revises: 402cad3270d9
Create Date: 2025-06-18 10:54:27.957134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61159146ed7'
down_revision = '402cad3270d9'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
#         # batch_op.drop_constraint("fk_restaurant_pizza_pizza_id", type_='foreignkey')
#         # batch_op.drop_constraint("fk_restaurant_pizza_pizza_id", type_='foreignkey')
#         batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
#         batch_op.create_foreign_key("fk_restaurant_pizza_pizza_id", 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')

#     # ### end Alembic commands ###

def upgrade():
    with op.batch_alter_table('restaurant_pizzas') as batch_op:
        batch_op.create_foreign_key(
            'fk_restaurant_pizza_pizza_id',
            'pizzas',
            ['pizza_id'],
            ['id'],
            ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_restaurant_pizza_restaurant_id',
            'restaurants',
            ['restaurant_id'],
            ['id'],
            ondelete='CASCADE'
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'])

    # ### end Alembic commands ###
